### PR TITLE
NLW-302 remove trailing slash problem on ngnix

### PR DESCRIPTION
**Pull request by euanfergusson**
fixing for ngnix

### CODE REVIEW

**Review by stephenwf — APPROVED** [review]

**Comment by elrossco22** [comment]
@euanfergusson @stephenwf can we merge this please ?

**Comment by elrossco22** [comment]
On another note, we may also want to pass this upstream if we can verify the problem exists there too ?

**Comment by stephenwf** [comment]
They fix it in the `.htaccess` maybe they could update their readme?

**Comment by elrossco22** [comment]
@stephenwf I would propose that, we should push any learnings that can be shared with others

**Comment by stephenwf** [comment]
Raised question on their GitHub, referencing it here:
https://github.com/omeka/omeka-s/issues/961

**Pull request merged**
