### PR TITLE
adds simplesamlphp redirect

### PR DESCRIPTION
**Pull request by Jenniferstrej**

### CODE REVIEW

**Comment by Jenniferstrej** [comment]
@stephenwf @fractos @euanfergusson

**Comment by stephenwf** [comment]
This should probably be only in the `rs-omeka-build` and copy a new nginx config in there as simplesaml won't be available by default

**Comment by elrossco22** [comment]
@Jenniferstrej In-light of @stephenwf's comments can this now be closed now ? as it should be in the RS specific build

**Comment by elrossco22** [comment]
@Jenniferstrej ?

**Pull request closed without merging**
