### PR TITLE
Omeka updates week beginning 22/5/17

### PR DESCRIPTION
**Pull request by stephenwf**

### CODE REVIEW

**Review by elrossco22 — APPROVED** [review]

**Comment by elrossco22** [comment]
@stephenwf @euanfergusson @apricot13  @andyvidual  This looks fairly safe to me, Can everyone please confirm that none of the modules they have created etc won't break. Previously the Omeka updates have updated the number of method parameters etc (something to be weary of)

**Comment by stephenwf** [comment]
I can't see any issues, can't see any method signature changes

**Comment by apricot13** [comment]
Nothing I can see from my side - only that one change to the Api Controller looks like it could cause issues.

**Comment by elrossco22** [comment]
@stephenwf we should probably get this merged today and get into the release cycle we planned for the automated pull happening every friday and being merged every monday

**Comment by stephenwf** [comment]
Sounds good, what about the conflicts, are there changes to the build steps?

**Comment by elrossco22** [comment]
@stephenwf 
`- nvm install node
 - - nvm use node
 + - nvm install 7
 + - nvm use 7`

is the build change .. sigh

**Pull request closed without merging**
