### PR TITLE
Create makeDockerfiles.sh

### PR DESCRIPTION
**Pull request by elrossco22**
@stephenwf we'll need to rmeove the apache builds now

### CODE REVIEW

**Review by stephenwf — APPROVED** [review]

**Comment by stephenwf** [comment]
Thats fine, we can keep the configuration, and just remove it from the matrix

**Comment by elrossco22** [comment]
@stephenwf can you please remove it as its your magic in play ? 👍

**Comment by stephenwf** [comment]
done!

**Comment by elrossco22** [comment]
@stephenwf the build is broken :(

**Pull request merged**
